name: Build executables on release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install `uv`
        uses: astral-sh/setup-uv@v6.0.1
        with:
          version: "0.7.9"

      - name: Set version
        shell: bash
        run: echo "VERSION=$(uvx hatch version | sed -r 's/^([[:digit:]]+(\.[[:digit:]]+){1,3}).*$/\1/')" >> "$GITHUB_ENV"

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13.2"

      - name: Install requirements
        run: uv sync --all-extras --frozen

      - name: Build executable
        run: >
          uv run nuitka
          --product-name=BUGS
          --product-version=${{ env.VERSION }}
          --file-description="BUGS: BackUp Game Saves"
          --copyright="2025 Theo Court. Licensed under the Mozilla Public License v2.0."
          --onefile
          --assume-yes-for-downloads
          --python-flag=-m
          ./src/bugs

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build for ${{ runner.os }}
          path: |
            bugs.exe
            bugs.bin

      - name: Add to release
        if: ${{ github.event_name == 'release' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} bugs.exe bugs.bin
